src/main/java/ussum/homepage/application/comment/controller/CommentController.java
src/main/java/ussum/homepage/application/comment/service/CommentService.java
src/main/java/ussum/homepage/application/comment/service/dto/PostCommentListResponse.java
src/main/java/ussum/homepage/application/reaction/controller/PostCommentReactionController.java
src/main/java/ussum/homepage/application/reaction/service/PostCommentReactionService.java
src/main/java/ussum/homepage/application/reaction/service/dto/request/PostCommentReactionCreateRequest.java
src/main/java/ussum/homepage/application/reaction/service/dto/response/PostCommentReactionResponse.java
src/main/java/ussum/homepage/domain/comment/service/formatter/PostCommentFormatter.java
src/main/java/ussum/homepage/domain/reaction/PostCommentReaction.java
src/main/java/ussum/homepage/domain/reaction/PostCommentReactionRepository.java
src/main/java/ussum/homepage/domain/reaction/exception/PostCommentReactionException.java
src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionAppender.java
src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionFormatter.java
src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionModifier.java
src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionReader.java
src/main/java/ussum/homepage/domain/reaction/service/formatter/PostCommentReactionFormatter.java
src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
src/main/java/ussum/homepage/infra/jpa/comment/entity/CommentType.java
src/main/java/ussum/homepage/infra/jpa/comment/entity/PostCommentEntity.java
src/main/java/ussum/homepage/infra/jpa/postlike/entity/Reaction.java
src/main/java/ussum/homepage/infra/jpa/reaction/PostCommentReactionMapper.java
src/main/java/ussum/homepage/infra/jpa/reaction/PostCommentReactionRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/reaction/entity/PostCommentReactionEntity.java
src/main/java/ussum/homepage/infra/jpa/reaction/repository/PostCommentReactionJpaRepository.java

---
- PostComment 관련 오타 및 자잘한 fix
- CreatePostCommentReaction api(테스트중)
- DeletePostCommentReaction api(테스트중)
<참고사항>
- 현재 좋아요를 추가하는 기능만 있어서 굳이 반응 타입(like or unlike)을 request dto를 받아야하는 의문이 있었지만, 추후 싫어요까지 생길수 있는 확장성을 고려하여 request dto로 like, unlike를 받는 것이 더 좋다고 판단함(+현우 생각)
---
- Fixes : #25  (수정중인 이슈)
- Ref : #18  (참고할 이슈)
---
---

[fix] postcomment 자잘한 수정 및 postcommentreaction api 구현  

---

src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
src/main/java/ussum/homepage/application/reaction/service/PostCommentReactionService.java
src/main/java/ussum/homepage/application/reaction/service/PostReactionService.java
src/main/java/ussum/homepage/application/reaction/service/dto/request/PostReactionCreateRequest.java
src/main/java/ussum/homepage/application/reaction/service/dto/response/PostReactionResponse.java
src/main/java/ussum/homepage/domain/post/exception/PostException.java
src/main/java/ussum/homepage/domain/postlike/PostReaction.java
src/main/java/ussum/homepage/domain/postlike/PostReactionRepository.java
src/main/java/ussum/homepage/domain/postlike/service/PostReactionAppender.java
src/main/java/ussum/homepage/domain/postlike/service/PostReactionFormatter.java
src/main/java/ussum/homepage/domain/postlike/service/PostReactionManager.java
src/main/java/ussum/homepage/domain/postlike/service/PostReactionModifier.java
src/main/java/ussum/homepage/domain/postlike/service/PostReactionReader.java
src/main/java/ussum/homepage/domain/postlike/service/exception/PostReactionException.java
src/main/java/ussum/homepage/domain/postlike/service/formatter/PostReactionFormatter.java
src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionModifier.java
src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionReader.java
src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
src/main/java/ussum/homepage/infra/jpa/postlike/PostLikeMapper.java
src/main/java/ussum/homepage/infra/jpa/postlike/PostReactionMapper.java
src/main/java/ussum/homepage/infra/jpa/postlike/PostReactionRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/postlike/entity/PostReactionEntity.java
src/main/java/ussum/homepage/infra/jpa/postlike/repository/PostReactionJpaRepository.java

---
- post(게시글)에 좋아요/싫어요를 추가합니다.
- post(게시글)에 좋아요/싫어요를 삭제합니다.
---
- Resolves : #24  
---
---

[feat] : post reaction api

---

build.gradle
src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
src/main/java/ussum/homepage/application/reaction/service/dto/request/PostReactionCreateRequest.java
src/main/java/ussum/homepage/global/config/SecurityConfig.java
src/main/java/ussum/homepage/infra/config/SwaggerConfig.java

---
- swagger setting 추가 및 post_reaction api swagger 적용 예시 
- swagger local path : http://localhost:8080/swagger-ui/index.html 
---
- Resolves : #32 
---
---

[feat] #32 swagger setting

---

src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
src/main/java/ussum/homepage/infra/jpa/user/entity/MajorCode.java

---
- togglePostReaction uri 수정 (postId 적용안되어 있었음)
- MajorCode Enum 값 60개 추가 -> 각 대학 별 학과
---
- Fixes : #38 
- Ref : #36 
---
---

[refactor] #38 MajorCode Enum 값 추가 

---

src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostEntity.java
src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/AuditPostResponseDto.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/LostPostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/PartnerPostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/PetitionPostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/PostListRes.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/PostListResDto.java
src/main/java/ussum/homepage/domain/post/Post.java
src/main/java/ussum/homepage/domain/post/PostRepository.java
src/main/java/ussum/homepage/domain/post/service/PostReader.java
src/main/java/ussum/homepage/domain/postlike/PostReactionRepository.java
src/main/java/ussum/homepage/domain/postlike/service/PostReactionReader.java
src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
src/main/java/ussum/homepage/infra/jpa/post/entity/Status.java
src/main/java/ussum/homepage/infra/jpa/post/repository/PostJpaRepository.java
src/main/java/ussum/homepage/infra/jpa/postlike/PostReactionRepositoryImpl.java

---
- 게시판 별 dto 생성 : 확장성을 위해 똑같은 필드를 가진 dto라도 따로 생성하였음
- switch문 사용해서 첨에 구현했다가 map  방식으로 변경(스위치문은 주석처리로 넣어놓음)
- dto는 일단 postList패키지에 몰아넣었습니다 이것도 어떻게 처리할지 조언 부탁드립니다
- 좋아요 세기 query dsl
---
#45 
---
dto처리 로직에서 어떻게 하면 좋을지 의견 부탁 드립니다
---

[feat] : 게시판 조회 별 dto 반환 로직 구현

---

src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
src/main/java/ussum/homepage/domain/member/Member.java
src/main/java/ussum/homepage/domain/member/MemberRepository.java
src/main/java/ussum/homepage/infra/jpa/member/MemberMapper.java
src/main/java/ussum/homepage/infra/jpa/member/MemberRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MemberEntity.java

---
- Domain Member내 createMember 메소드 추가 후 로직 수정
---
- Related to : #54
---

[fix] : OnBoarding 관련 메소드 수정

---

src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/PostService.java
src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
src/main/java/ussum/homepage/domain/post/PostFileRepository.java
src/main/java/ussum/homepage/domain/post/service/PostFileAppender.java
src/main/java/ussum/homepage/infra/jpa/post/PostFileRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/post/entity/BoardCode.java

---
- 자료집 리스트 api 구현
---
- Related to : #50 
---
---

[feat] #50 자료집 리스트 api 구현

---

src/main/java/ussum/homepage/application/comment/controller/CommentController.java
src/main/java/ussum/homepage/application/comment/controller/PostCommentManagerController.java
src/main/java/ussum/homepage/application/comment/controller/PostReplyCommentController.java
src/main/java/ussum/homepage/application/post/controller/PostController.java
src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/PetitionPostDetailResponse.java
src/main/java/ussum/homepage/application/reaction/controller/PostCommentReactionController.java
src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
src/main/java/ussum/homepage/application/reaction/controller/PostReplyCommentReactionController.java
src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
src/main/java/ussum/homepage/domain/post/service/factory/BoardFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/GeneralBoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/NoticeBoardImpl.java
src/main/java/ussum/homepage/infra/jpa/comment/PostCommentMapper.java
src/main/java/ussum/homepage/infra/jpa/comment/PostCommentRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/comment/PostReplyCommentMapper.java
src/main/java/ussum/homepage/infra/jpa/comment/PostReplyCommentRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/comment/entity/PostCommentEntity.java
src/main/java/ussum/homepage/infra/jpa/comment/entity/PostReplyCommentEntity.java
src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java
src/main/java/ussum/homepage/infra/jpa/post/entity/OngoingStatus.java
src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java

---
- BoardFactory id null 문제 해결 
- Category Enum 값 추가 
- OnGoingStatus Enum 값 한국어 변경
- 댓글, 대댓글 수정 lastEditedAt 필드 업데이트 메소드 추가
- swagger description 추가 
---
- Resolves : #67 
---
---

[fix] #67 BoardFactory id null 문제 해결 

---

src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
src/main/java/ussum/homepage/domain/post/Post.java
src/main/java/ussum/homepage/domain/post/PostRepository.java
src/main/java/ussum/homepage/domain/post/service/PostReader.java
src/main/java/ussum/homepage/domain/post/service/factory/BoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/GeneralBoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/NoticeBoardImpl.java
src/main/java/ussum/homepage/global/config/CorsConfig.java
src/main/java/ussum/homepage/global/config/SecurityConfig.java
src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
src/main/java/ussum/homepage/infra/jpa/group/entity/GroupCode.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java
src/main/java/ussum/homepage/infra/jpa/post/entity/OngoingStatus.java
src/main/java/ussum/homepage/infra/utils/DateUtils.java

---
- dateUtil 구현 및 적용
- dto 짜잘한 부분 추가
- enum null 처리 추가 
- isEmergency부분 로직 좀 변경 필요 일단 api 테스트용으로 넣어놓고 대강 짜긴 함  최대한 필드 추가 안하게 하려고 category에 emergency 넣고 했는데 좀 바꿔야 할듯
---
---
---

 [refactor] #50 api 테스트 중 오류해결, 파라미터 수정 및 dto 수정

---

src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/DataPostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/AuditPostResponseDto.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/LostPostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/PartnerPostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/PetitionPostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/PostListResDto.java
src/main/java/ussum/homepage/domain/post/PostRepository.java
src/main/java/ussum/homepage/domain/post/service/PostReader.java
src/main/java/ussum/homepage/domain/post/service/factory/BoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/GeneralBoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/NoticeBoardImpl.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java

---
- 작업한 내용 1
- 작업한 내용 2
---
---
---

[refactor] #50 category로 필터링 로직 추가 및 dto 필드 수정

---

src/main/generated/ussum/homepage/infra/jpa/user/entity/QUserEntity.java
src/main/java/ussum/homepage/application/post/controller/PostManageController.java

---
- 파라미터 required 수정
---
- Related to : #54 
---

[fix] : postFile api 파라미터 required false

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/DataPostResponse.java
src/main/java/ussum/homepage/domain/comment/service/formatter/QuadFunction.java

---
- 자료집 게시판 리스트 반환 dto 수정
- quadfuction 추가
---
---
---

[refactor] #50 자료집 게시판 dto 수정

---

src/main/java/ussum/homepage/application/post/controller/PostController.java
src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java

---
- 게시물 삭제 시 연관된 파일 삭제 안되는 문제 해결
---
---
---

[fix] #78 게시물 삭제 시 연관된 파일 삭제 안되는 문제 해결

---

src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostFileEntity.java
src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/DataPostResponse.java
src/main/java/ussum/homepage/domain/post/PostFile.java
src/main/java/ussum/homepage/domain/post/PostFileRepository.java
src/main/java/ussum/homepage/domain/post/PostRepository.java
src/main/java/ussum/homepage/domain/post/service/PostFileAppender.java
src/main/java/ussum/homepage/domain/post/service/PostReader.java
src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
src/main/java/ussum/homepage/infra/jpa/post/PostFileMapper.java
src/main/java/ussum/homepage/infra/jpa/post/PostFileRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/post/entity/FileCategory.java
src/main/java/ussum/homepage/infra/jpa/post/entity/PostFileEntity.java

---
- fileCategory 필드 추가 
- 자료집게시판 검색 생성 로직 수정
---
---
---

[refactor] #50 자료집게시판 검색, 생성 로직 수정

---

src/main/java/ussum/homepage/infra/jpa/post/PostFileMapper.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[refactor] #50 fileCategory null 처리

---

src/main/java/ussum/homepage/domain/post/service/PostFileReader.java

---
- 파일,이미지 변수에 복수형 s 추가
---
---
---

[fix] 파일,이미지 변수에 s 추가

---

src/main/java/ussum/homepage/HomepageApplication.java
src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java

---
- 게시물 content 필드 Lob 추가
- 스케줄러 사용을 위한 @EnableScheduling 선언
---
---
---

[refactor] 게시물 content 필드 Lob 추가

---

src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java

---
- 인기청원 게시물 좋아요 순으로 반환 안되는 문제 해결
---
---
---

[fix] 인기청원 게시물 좋아요 순으로 반환 안되는 문제 해결

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/postSave/PostFileDeleteResponse.java
src/main/java/ussum/homepage/infra/utils/S3utils.java

[feat] : S3 객체 삭제 처리 수정 

---

src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java

[fix] : PostUpdateRequest 수정

---

src/main/generated/ussum/homepage/infra/jpa/comment/entity/QPostCommentEntity.java
src/main/generated/ussum/homepage/infra/jpa/comment/entity/QPostReplyCommentEntity.java
src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostEntity.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/postSave/PostFileMediatorResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postSave/PostFileResponse.java
src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
src/main/java/ussum/homepage/application/user/service/dto/response/CouncilLoginResponse.java
src/main/java/ussum/homepage/infra/jpa/member/repository/MemberJpaRepository.java
src/main/java/ussum/homepage/infra/utils/S3utils.java

---
- PostFile API 수정
- 온보딩 로직 수정
---
---

[fix, refactor] : PostFile API 수정, 온보딩 로직 수정

---

src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java

---
- 온보딩 예외처리 if문 수정
---
- Related to : #84
---

[fix] : 온보딩 if문 수정

---

src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java

---
- 온보딩 자료형 불일치 해결
---
- Related to : #84
---

[fix] : 자료형 불일치 문제 해결

---

src/main/java/ussum/homepage/application/comment/service/PostCommentManageService.java
src/main/java/ussum/homepage/application/comment/service/dto/response/PostCommentResponse.java
src/main/java/ussum/homepage/application/comment/service/dto/response/PostReplyCommentResponse.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/PetitionPostDetailResponse.java
src/main/java/ussum/homepage/application/reaction/service/PostCommentReactionService.java
src/main/java/ussum/homepage/application/reaction/service/PostReactionService.java
src/main/java/ussum/homepage/domain/comment/service/formatter/PostCommentFormatter.java
src/main/java/ussum/homepage/domain/comment/service/formatter/PostReplyCommentFormatter.java
src/main/java/ussum/homepage/domain/post/service/formatter/PostDetailFunction.java
src/main/java/ussum/homepage/domain/postlike/PostReactionRepository.java
src/main/java/ussum/homepage/domain/postlike/service/PostReactionManager.java
src/main/java/ussum/homepage/domain/postlike/service/PostReactionReader.java
src/main/java/ussum/homepage/domain/reaction/PostCommentReactionRepository.java
src/main/java/ussum/homepage/domain/reaction/PostReplyCommentReactionRepository.java
src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionManager.java
src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionReader.java
src/main/java/ussum/homepage/domain/reaction/service/PostReplyCommentReactionManager.java
src/main/java/ussum/homepage/infra/jpa/postlike/PostReactionRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/postlike/repository/PostReactionJpaRepository.java
src/main/java/ussum/homepage/infra/jpa/reaction/PostCommentReactionRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/reaction/PostReplyCommentReactionRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/reaction/repository/PostCommentReactionJpaRepository.java
src/main/java/ussum/homepage/infra/jpa/reaction/repository/PostReplyCommentReactionJpaRepository.java

isLiked 필드를 게시물 조회, 댓글 대댓글 조회 반환값에 추가하여 해당 사용자가 해당 컨텐츠에 대하여 좋아요를 눌렀는지 안눌렀는지 판단 여부 반환
---
- 해당 사용자가 좋아요를 눌렀는지 확인 여부 필드 추가
- isLiked 필드를 게시물 조회, 댓글 대댓글 조회 반환값에 추가하여 해당 사용자가 해당 컨텐츠에 대하여 좋아요를 눌렀는지 안눌렀는지 판단 여부 반환
---
- Resolves : #96 
---
---

[feat] : #96 해당 사용자가 좋아요를 눌렀는지 확인 여부 필드 추가

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/AuditPostResponseFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/DataPostResponseFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/LostPostResponseFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/NoticePostResponseFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/PartnerPostResponseFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/PetitionPostResponseFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/PostListResponseFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/PostResponseFactoryProvider.java
src/test/java/ussum/homepage/application/post/service/PostManageServiceTest.java

---
- 게시글 리스트 조회 factory 패턴으로 리팩토링
---
- Related to : #98 
---
---

[refactor] #98 게시글 리스트 조회 factory 패턴으로 리팩토링

---

src/main/java/ussum/homepage/infra/jpa/group/GroupMapper.java
src/main/java/ussum/homepage/infra/jpa/group/entity/GroupCode.java
src/main/java/ussum/homepage/infra/jpa/member/MemberMapper.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MajorCode.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java

---
-  Code Enum 한글 반환 처리
---
---

[feat] : Code Enum 한글 반환 처리

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
src/main/java/ussum/homepage/application/user/service/OAuthService.java
src/main/java/ussum/homepage/application/user/service/dto/response/CouncilLoginResponse.java
src/main/java/ussum/homepage/domain/member/service/MemberReader.java

[fix, hotfix] : 자치기구 로그인 수정, 게시물 수정 api

---

src/main/java/ussum/homepage/application/admin/service/AdminService.java
src/main/java/ussum/homepage/application/admin/service/dto/request/CouncilSignInRequest.java
src/main/java/ussum/homepage/domain/group/GroupRepository.java
src/main/java/ussum/homepage/domain/group/service/GroupReader.java
src/main/java/ussum/homepage/domain/member/service/MemberAppender.java
src/main/java/ussum/homepage/domain/user/User.java
src/main/java/ussum/homepage/infra/jpa/group/GroupRepositoryImpl.java

[feat] : 자치기구 회원가입 수정

---

src/main/java/ussum/homepage/application/post/service/dto/response/DataPostResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/FileResponse.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/DataPostResponseFactory.java
src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[fix] 자료집 조회 dto 수정

---

src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[hotfix] 페이지 쿼리dsl 로직 수정

---

src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/domain/post/PostRepository.java
src/main/java/ussum/homepage/domain/post/service/PostReader.java
src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java

---
- 게시물 Status NEW -> GENERAL 상태 변경 스케줄러 추가 
- 자료집 게시판 검색 api 추가 
---
- Resolves : #108 
---
---

[refactor, feat] #108 게시물 NEW Status 3일 체크 로직 및 자료집 게시판 검색 api 추가 

---

src/main/java/ussum/homepage/application/acl/service/AclManageService.java
src/main/java/ussum/homepage/application/acl/service/factory/AclStrategy.java
src/main/java/ussum/homepage/application/acl/service/factory/AnonymousAclStrategy.java
src/main/java/ussum/homepage/application/acl/service/factory/EveryoneAclStrategy.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/infra/jpa/acl/repository/PostAclJpaRepository.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

acl 적용 테스트

---

src/main/java/ussum/homepage/application/comment/controller/PostCommentManagerController.java
src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/global/config/SecurityConfig.java
src/main/java/ussum/homepage/global/config/auth/UserIdArgumentResolver.java
src/main/java/ussum/homepage/global/jwt/JwtFilter.java

---
- 토큰을 넣으면 로그인 유저, 토큰을 넣지 않으면 비로그인 유저 -> 이를 통해 isAuthor 필드의 값이 달라짐
- SecurityConfig에 해당 로직이 필요한 api(게시물 단건 조회, 댓글 전체 조회 등) .permitAll()을 하여 토큰이 필요없는 다른 api와 분리하여 처리
- JwtFilter에서 토큰이 있으면 처리하고 없으면 null
---
- Resolves : #110 
---
---

[feat] #110 비로그인 로그인 모두 허용하는 로직 추가

---

src/main/generated/ussum/homepage/infra/jpa/acl/entity/QPostAclEntity.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
src/main/java/ussum/homepage/domain/post/service/PostModifier.java
src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
src/main/java/ussum/homepage/infra/jpa/post/entity/Status.java

[hotfix] update로직 

---

src/main/java/ussum/homepage/application/admin/controller/AdminController.java
src/main/java/ussum/homepage/domain/csv_user/StudentCsv.java
src/main/java/ussum/homepage/infra/csvBatch/config/FileItemReaderJobConfig.java
src/main/java/ussum/homepage/infra/csvBatch/csv/CSVReader.java
src/main/java/ussum/homepage/infra/csvBatch/csv/CSVWriter.java
src/main/java/ussum/homepage/infra/jpa/csv_user/StudentCsvMapper.java
src/main/java/ussum/homepage/infra/jpa/csv_user/entity/StudentCsvEntity.java

---
- batch 필드명 수정
---
- Related to : #123 
---

[fix] : batch 필드명 수정

---

src/main/java/ussum/homepage/application/admin/controller/AdminController.java

---
- consume 설정
---
- Related to : #123
---

[fix] #123 AdminController consume설정

---

src/main/java/ussum/homepage/infra/csvBatch/csv/CSVReader.java
src/main/java/ussum/homepage/infra/utils/S3utils.java

---
- filepath수정
---
- Related to : #123 
---

[fix] #123 filepath 수정

---

build.gradle
src/main/java/ussum/homepage/global/config/SecurityConfig.java

---
- 빌드 업무 수정(actuator 관련 라이브러리)
---
- Related to  #127
---

[chore] : actuator 의존성 설정

---

src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
src/main/java/ussum/homepage/infra/csvBatch/config/FileItemReaderJobConfig.java

---
- batch 수정
- 온보딩 수정
---
- Related to : #123 
---

[fix] batch및  온보딩 오류 수정

---

src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java

---
- getMajor로 다시 수정
---
- Related to : #123 
---

[fix] #123 getMajor로 다시 수정

---

src/main/java/ussum/homepage/application/user/controller/UserController.java
src/main/java/ussum/homepage/application/user/service/UserService.java
src/main/java/ussum/homepage/application/user/service/dto/request/TokenRequest.java
src/main/java/ussum/homepage/application/user/service/dto/response/UserInfoResponse.java
src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
src/main/java/ussum/homepage/global/config/SecurityConfig.java

---
- 토큰으로 정보 조회
---
- Related to : #84
---

[add] PASSU 토큰 정보 조회 로직

---

src/main/java/ussum/homepage/application/user/controller/UserController.java
src/main/java/ussum/homepage/application/user/service/dto/request/TokenRequest.java

---
- class로 변경
---
- Related to : #84
---

[fix] record to class

---

src/main/java/ussum/homepage/application/user/controller/UserController.java

[fix] @ResponseBody 삭제

---

src/main/java/ussum/homepage/application/user/controller/UserController.java

---
- Header로 토큰 입력받는 것으로 수정
---
---

[fix] Header로 토큰 입력받는 것으로 수정

---

src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java

---
- 문예창작전공, 영화예술전공 예외처리
---
ex)
- Fixes : #84 
---

[fix] 문예창작전공, 영화예술전공 예외처리

---

src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
src/main/java/ussum/homepage/infra/jpa/post/entity/SuggestionTarget.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[fix] :#142 SuggestionTarget null 이슈 해결

---

src/main/java/ussum/homepage/global/config/CorsConfig.java

---
- 작업한 내용 1
- 작업한 내용 2
---
Resolves #152 
---
---

[refactor]: #152 개발 도메인 CORS 설정

---

src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[fix]:category 필드 다중매핑

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[feat]:비로그인 목록조회 처리

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/RightsPostResponse.java
src/main/java/ussum/homepage/domain/post/PostRepository.java
src/main/java/ussum/homepage/domain/post/service/PostReader.java
src/main/java/ussum/homepage/domain/post/service/factory/BoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/GeneralBoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/NoticeBoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/SuggestionBoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/PostListResponseFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/RightsPostResponseFactory.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/SuggestionPostResponseFactory.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[refactor] : #142 목록조회 엔드포인트 변경 및 리팩토링

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java

---
- 목록 조회 수정
---
ex)
- Fixes : #142 
---
---

[fix]: #142 타 자치기구 목록조회 수정

---

src/main/java/ussum/homepage/domain/acl/service/post/PostAclHandler.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[feat] : #142 댓글 권한 추가

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[feat] : #142 관리자 권한추가

---

src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
src/main/java/ussum/homepage/infra/jpa/comment/PostCommentRepositoryImpl.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[feat]: #142 공식댓글 수정 예외처리

---

.github/workflows/main-cicd.yml
.gitignore
src/main/java/ussum/homepage/global/logging/LoggingAspect.java

---
- 요청오면 요청과 응답관련된 내용 로그에 남도록 했습니다.
- 요청 관련해서 토큰 필요없으면 userId에 null이라 뜨고 Request body는 없으면 0이라 뜹니다.
- 응답 로그는 api path랑 Response Body 로그 남습니다.
---
resolved #168 
---
- 추가 되어야 할 로그 정보(캡쳐본엔 없는데 쿼리 로그도 남음)
- 거슬리는 것들 등등
---

[feat] 로깅 세팅

---

.github/workflows/main-cicd.yml

---
- logback 생성 스크립트 중 잘못된 부분 있어 수정
---
Resolves #174 
---

[feat] cicd 스크립트 수정(logback 관련)

---

src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
src/main/java/ussum/homepage/domain/acl/service/post/PostAclManager.java
src/main/java/ussum/homepage/domain/member/Member.java
src/main/java/ussum/homepage/domain/member/service/MemberAppender.java
src/main/java/ussum/homepage/infra/jpa/acl/entity/Target.java
src/main/java/ussum/homepage/infra/jpa/member/MemberMapper.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MemberEntity.java

---
- member 테이블에 is_verified 상태 추가 
- is_verified 가 false (인증미완료)로 신입생일 경우 읽기 권한만 받게 수정
---
ex)
---
---

[feat] : 인증완료자/ 인증미완료자(신입생) 상태 추가

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java

---
- 건의게시판 키워드 검색 API 에서 page, q 없어도 리스트 내려가게 수정
---
ex)
---
---

[feat] #181 건의게시판 키워드 검색 API 수정(page, q없어도 리스트 내려가게)

---

build.gradle
src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostEntity.java
src/main/generated/ussum/homepage/infra/jpa/post/entity/QRightsDetailEntity.java
src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/DataPostDetailResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/DataPostResponse.java
src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/DataPostResponseFactory.java
src/test/java/ussum/homepage/application/post/service/PostManageServiceTest.java

- Factory 패턴에서 분리하여 독립적인 API로 구현
- 게시글 번호를 통한 단건조회 기능 분리
---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
일단 배포를 위해 api 분리해서 넣어놨어요
---

feat: 자료집게시판 상세조회 API 분리 구현

---

src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/domain/post/PostRepository.java
src/main/java/ussum/homepage/domain/post/service/PostReader.java
src/main/java/ussum/homepage/domain/post/service/factory/BoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/GeneralBoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/NoticeBoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/QnABoardImpl.java
src/main/java/ussum/homepage/domain/post/service/factory/SuggestionBoardImpl.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java

---
- 질의응답게시판 검색 API qnaTarget 구분하게 수정
---
ex)
---
---

[feat] #187 질의응답게시판 검색 API qnaTarget 구분하게 수정

---

src/main/java/ussum/homepage/domain/comment/service/formatter/PostCommentFormatter.java
src/main/java/ussum/homepage/domain/comment/service/formatter/PostReplyCommentFormatter.java

---
- 질의응답게시판 댓글 수정
---
ex)
---
---

[feat] 질의응답게시판 댓글 응답 수정

---

src/main/java/ussum/homepage/domain/member/MemberRepository.java
src/main/java/ussum/homepage/domain/member/service/MemberManager.java
src/main/java/ussum/homepage/infra/jpa/member/MemberRepositoryImpl.java

---
- 질의응답게시판 오피셜 댓글 로직 추가
- 작업한 내용 2
---
ex)
---
---

[feat] #185 질의응답게시판 오피셜 댓글 로직 추가

---

src/main/java/ussum/homepage/global/config/CorsConfig.java

---
- 스웨거 CORS
---
ex)
---
---

[feat] #196 swagger cors

---

src/main/java/ussum/homepage/global/logging/LoggingAspect.java

---
- Body log 형식 Pretty Print로 변경
- 응답 로그에 실행시간 추가
---
Resolves #199 
---

[feat] LoggingAspect 수정

---

src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/user/service/dto/response/CollegeAndDepartmentResponse.java

---
- 단과대 학과 조회 api 구현
---
ex)
---
---

[feat] #204 단과대 학과 조회 api

---

src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/user/service/dto/response/CollegeAndDepartmentResponse.java

---
- 단과대 학과 조회 api 수정
---
ex)
---
---

[feat] #204 단과대 학과 조회 api 수정

---

.github/workflows/develop-cicd.yml
.github/workflows/main-cicd.yml
docker-compose.yml
scripts/deploy.sh

---
- 개발 서버 cicd 스크립트 수정
- 컨테이너 실행 시 yml 동적 생성하는 방식으로 변경
- 운영  서버 cicd 수정
- deploy.sh에 YML 환경 변수 넘겨 deploy.sh 실행 시 yml 동적 생성
- 둘다 SPRING_CONFIG_LOCATION 직접 지정
---
Resolves #207 
---
- 스크립트 이상 없는 지
- 설정 문제 없는 지(마운트, CONFIG 경로 지정 등)
---

[feat] yml 생성 방식 변경

---

.github/workflows/develop-cicd.yml
.github/workflows/main-cicd.yml
docker-compose.yml
scripts/deploy.sh
src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/NoticePostDetailResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/ServicePostDetailResponse.java
src/main/java/ussum/homepage/application/user/service/dto/response/CollegeAndDepartmentResponse.java
src/main/java/ussum/homepage/global/config/CorsConfig.java
src/main/java/ussum/homepage/infra/config/SwaggerConfig.java

[merge] 최신 배포 사항 반영

---

src/main/java/ussum/homepage/application/post/controller/PostManageController.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/domain/post/PostRepository.java
src/main/java/ussum/homepage/domain/post/service/PostReader.java
src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java

---
- 마이페이지 검색 API, 조회 API 응답 수정
---
ex)
---
---

[feat] #169 마이페이지 검색 API, 조회 API 응답 수정

---

src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/QnAPostDetailResponse.java

---
- 질의응답게시판 디테일 qnaTargetCode 추가
---
ex)
---
---

[feat] #185 질의응답게시판 디테일 qnaTargetCode 추가

---

src/main/java/ussum/homepage/domain/acl/service/post/PostAclHandler.java

---
- 질의응답게시판 자치기구 댓글 권한 수정
---
ex)
---
---

[feat] #185 질의응답게시판 자치기구 댓글 권한 수정

---

src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java

---
- Post 검색 결과에서 EMERGENCY_NOTICE 상태인 게시물이 최상단에 노출되도록 정렬 로직 추가
- QueryDSL orderBy 절에 status 기준 정렬 조건 추가 (EMERGENCY_NOTICE -> 0, 그 외 -> 1)
- 동일 Status 내에서는 기존과 같이 생성일자(createdAt) 내림차순 정렬 유지
---
---
- orderBy 절에서 status 정렬 조건 추가 시 현재 방식이 최적의 방법인지 검토 부탁드립니다
- 다른 상태값들에 대한 우선순위 정렬이 추가될 가능성이 있는지, 있다면 현재 구조가 확장성 있게 설계되었는지 리뷰 부탁드립니다
---

feat: 게시물 검색 시 긴급공지 우선 정렬 기능 추가

---

src/main/java/ussum/homepage/application/post/service/dto/request/GeneralPostCreateRequest.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

fix: isNotice에따른 게시물 상태 변경

---

src/main/java/ussum/homepage/application/user/controller/UserController.java

---
- swagger userId hidden
---
ex)
---
---

[fix] #224 userId hidden

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/global/error/status/ErrorStatus.java

---
- 질의응답게시판 이메일 발송 임시
---
ex)
---
---

[fix] #229 질의응답게시판 이메일 발송 임시

---

src/main/java/ussum/homepage/domain/acl/service/post/PostAclHandler.java

---
- 질의응답게시판 자치기구 계정 댓글 삭제 권한 추가
---
ex)
---
---

[fix] #234 질의응답게시판 자치기구 계정 댓글 삭제 권한 추가

---

src/main/java/ussum/homepage/application/user/service/dto/response/UserInfoResponse.java
src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MajorCode.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java

---
- 새로 추가된 학과/ 단과대 업데이트
- /user-info 수정
- 온보딩 예외처리
---
ex)
---
---

[Fix] #238 PASSU 개강행사

---

src/main/java/ussum/homepage/infra/jpa/member/entity/MajorCode.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java

---
- 학과/단과대 업데이트
---
ex)
---
---

[fix] : 학과/단과대 업데이트

---

src/main/java/ussum/homepage/application/user/service/dto/response/UserInfoResponse.java
src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java

---
- 재학생 대조 로직 일부 제거 및 /user-info 자치기구계정 방어처리
---
ex)
---
---

[feat] : 재학생 대조 로직 일부 제거 및 /user-info 자치기구계정 방어처리

---

src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
src/main/java/ussum/homepage/global/error/status/ErrorStatus.java

---
- 재학생 대조 로직 수정
---
ex)
---
---

[feat] : 재학생 대조 로직 수정

---

src/main/java/ussum/homepage/global/config/SecurityConfig.java

---
- 디스코드 봇에서 사용하는 API whitelist에 추가
---
ex)
---
---

[fix] : #252 디스코드 봇에서 사용하는 API whitelist에 추가

---

build.gradle
src/main/java/ussum/homepage/application/user/controller/OnBoardingController.java
src/main/java/ussum/homepage/global/aspect/logging/LoggingAspect.java
src/main/java/ussum/homepage/global/aspect/ratelimit/RateLimitAspect.java
src/main/java/ussum/homepage/global/config/custom/RateLimit.java
src/main/java/ussum/homepage/global/error/exception/ExceptionAdvice.java
src/main/java/ussum/homepage/global/error/exception/RateLimitException.java
src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
src/main/java/ussum/homepage/infra/config/RedisConfig.java

---
- 같은 IP 요청 다량 감지 관련 요청사항이 들어와서 Rate Limiter 구현했습니다.
- AOP 활용
- ip별 요청 제한
- 클래스 별 어노테이션 적용 가능
- 온보딩 컨트롤러에 예시로 적용해놨습니다. 일단 1분에 요청 제한을 10개로 설정해놨고 바꿔야 될 시 바꾸면 됩니다!
---
Resolves #249 
---
- 코드 스멜
- 구현 잘못된 부분 있는 지
---

[feat] Rate Limiter 구현

---

src/main/java/ussum/homepage/application/comment/service/CommentService.java
src/main/java/ussum/homepage/domain/comment/PostCommentRepository.java
src/main/java/ussum/homepage/domain/comment/service/PostCommentModifier.java
src/main/java/ussum/homepage/infra/jpa/comment/PostCommentRepositoryImpl.java

---
- 질의응답게시판 공식 댓글 삭제 가능하게 수정
---
ex)
---
---

[fix] : #259 질의응답게시판 공식 댓글 삭제 가능하게 수정

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java

---
- 질의응답게시판 메일 포맷 수정
---
ex)
---
---

[feat] : #262 질의응답게시판 메일 포맷 수정

---

src/main/java/ussum/homepage/application/comment/service/CommentService.java
src/main/java/ussum/homepage/application/comment/service/dto/response/PostOfficialCommentResponse.java
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/domain/comment/PostCommentRepository.java
src/main/java/ussum/homepage/domain/comment/service/PostCommentModifier.java
src/main/java/ussum/homepage/infra/jpa/comment/PostCommentRepositoryImpl.java

---
- 공식댓글 삭제 가능하게 수정
- 메일 포맷 수정
---
ex)
---
---

[merge] 질의응답 게시판 공식댓글, 메일 포맷 수정

---

.github/workflows/develop-cicd.yml
docker-compose-dev.yml
src/main/java/ussum/homepage/application/health/healthController.java
src/main/java/ussum/homepage/global/config/SecurityConfig.java

---
- 컨테이너가 완전히 올라올 때 까지 대기하는 시간이 없어서, 헬스체크가 실패하는 경우가 발생했는데, 30초정도 대기시간을 주었습니다.
- 헬스체크 API를 수정했어야 했는데, 빼먹었어서 수정 후 올렸습니다.
---
- Fixes : #266 
- Ref : #269 #272

[refactor] #266 헬스체크 오류 수정 및 헬스체크 API 추가

---

.github/workflows/develop-cicd.yml

---
- 30초정도로는 바로 healthy 여부 판단이 안되어서, 2분으로 늘렸습니다.

[refactor] #266 컨테이너 상태 확인 대기 시간 수정

---

src/main/java/ussum/homepage/application/health/healthController.java

[feat] main cicd용 헬스체크 api 추가

---

src/main/java/ussum/homepage/application/health/healthController.java

[feat] main cicd용 헬스체크 white list 추가

---

src/main/java/ussum/homepage/application/comment/service/dto/response/PostCommentResponse.java
src/main/java/ussum/homepage/application/comment/service/dto/response/PostReplyCommentResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/QnAPostDetailResponse.java
src/main/java/ussum/homepage/application/post/service/dto/response/postList/QnAPostResponse.java
src/main/java/ussum/homepage/domain/post/service/factory/postList/QnAPostResponseFactory.java
src/main/java/ussum/homepage/domain/user/User.java

---
- 질의응답 게시판 이름은 '장*호'와 같이 마스킹해서 응답 내려주게 수정
---
---
---

[feat] : #285 질의응답게시판 이름 마스킹

---

build.gradle
src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/domain/post/service/GoogleSheetsReader.java
src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
src/main/java/ussum/homepage/infra/jpa/sheet_email/entity/CollegeDepartmentEmailEntity.java
src/main/java/ussum/homepage/infra/jpa/sheet_email/repository/CollegeDepartmentEmailJpaRepository.java

---
- 질의응답게시판 학생회 별 이메일 발송 로직 추가
---
---
---

[feat] : #290 질의응답게시판 학생회 별 이메일 발송 로직 추가

---

src/main/java/ussum/homepage/global/aspect/exception/ExceptionAlertAspect.java
src/main/java/ussum/homepage/global/aspect/logging/LoggingAspect.java
src/main/java/ussum/homepage/infra/utils/HttpUtils.java

---
- 요청, 응답 로그 구성 수정(각각 body 제거, 상태코드 추가)
- 에러 로그 추가
---
Resolves #287 
---

[refactor] 로그 구성 수정 및 추가

---

src/main/java/ussum/homepage/global/config/CorsConfig.java

---
- 더이상 사용하지 않는 vercel URL 및 GitHub Pages URL 제거
- 프론트엔드 변경사항 확인을 위한 Preview URL 추가
---
---
누구 리뷰 걸어야 할지 몰라서 제일 최근에 머지하신 인호님 걸었습니다 (ㅎㅎ)
---

[feat] CORS 허용 목록 업데이트

---

src/main/java/ussum/homepage/global/aspect/exception/ExceptionAlertAspect.java

---
- USER 관련 에러시 알림 미발송
---
Resolves #298 
---

[feat] 에러 알림 발송 조건 수정

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/infra/jpa/post/entity/BoardCode.java

---
- 기존 한글로 boardCode를 처리하였지만 영어로 처리하도록 수정
- 기존 enum BoardCode 클래스의 getEnumBoardCodeFromStringBoardCode() 메소드를 개선하여
- 한글 또는 영어로 처리 가능하도록 수정
- 영어 대소문자 구분없이 처리 가능
---
Resolves #302 
---
기존 코드에 최대한 영향이 없도록 기능 추가 및 개인적으로 테스트했는데, 혹시 문제가 생길 부분이 있을지 궁금합니다
---

[refactor] : boardCode를 한글이 아닌 영어로 처리

---

src/main/java/ussum/homepage/infra/config/SwaggerConfig.java

---
- 환경 변수로 swagger 요청 목적지 url을 관리하여 개발/운영 서버에 맞게 요청하도록 함
- application.yml 수정(notion에 반영 완료)
---
- Fixes : #306 
---
---

[fix] : Swagger에서 요청 주소 수정

---

src/main/java/ussum/homepage/infra/config/SwaggerConfig.java

---
- 기본 생성되는 url을 사용하면 http로 생성되어서 환경변수를 사용하는 방식으로 해야될 것 같습니다
---
#308 
---
---

[fix] #308 swagger 환경변수 재설정

---

src/main/java/ussum/homepage/application/post/service/PostManageService.java
src/main/java/ussum/homepage/infra/jpa/group/entity/GroupCode.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MajorCode.java
src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java
src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java

---
- 작업한 내용 1
- 작업한 내용 2
---
ex)
---
---

[fix] : 융합특성화자유전공 학부명 변경

---

src/main/java/ussum/homepage/infra/config/EmailListener.java

---
- 건의게시판(구 질의응답게시판) 로그 추가
---
---
---

[feat] 건의게시판(구 질의응답게시판) 로그 추가
